# Generated by Django 3.2.4 on 2021-06-03 15:39

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_title', models.CharField(max_length=255)),
                ('correct_attempts', models.IntegerField(default=0)),
                ('total_attempts', models.IntegerField(default=0)),
                ('max_marks', models.FloatField(default=0)),
                ('no_of_testcases', models.IntegerField(default=0)),
                ('question_desc', models.TextField(default='NA')),
                ('constraints', models.TextField(default='NA')),
                ('explanation', models.TextField(default='NA')),
                ('iformat', models.TextField(default='NA')),
                ('oformat', models.TextField(default='NA')),
                ('sampleInput', models.TextField(default='NA')),
                ('sampleOutput', models.TextField(default='NA')),
            ],
        ),
        migrations.CreateModel(
            name='Userdata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=10)),
                ('college', models.CharField(blank=True, max_length=255)),
                ('totalScore', models.IntegerField(default=0)),
                ('junior', models.BooleanField(default=False)),
                ('correctly_solved', models.IntegerField(default=0)),
                ('attempted', models.IntegerField(default=0)),
                ('latest_ac_time', models.DateTimeField(default=datetime.datetime(2021, 6, 3, 15, 39, 17, 27712))),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(default=0)),
                ('submission_time', models.DateTimeField(auto_now=True)),
                ('attempt', models.IntegerField(default=0)),
                ('status', models.CharField(default='NA', max_length=5)),
                ('accuracy', models.FloatField(default=0)),
                ('code', models.TextField(default='')),
                ('language', models.CharField(choices=[('cpp', 'C++'), ('c', 'C'), ('py', 'Python')], max_length=6)),
                ('question_id_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.question')),
                ('user_id_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
